/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/activities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search activities
         * @description Search for activities matching the specified filters.
         *     Results are paginated and ordered by schedule time.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter activities suitable for this age (>= 0) */
                    age?: number;
                    /** @description Filter by geographic area UUID */
                    area_id?: string;
                    /**
                     * @description Filter by pricing type:
                     *     - per_class: Individual class pricing
                     *     - per_month: Monthly subscription
                     *     - per_sessions: Package pricing
                     */
                    pricing_type?: "per_class" | "per_month" | "per_sessions";
                    /** @description Minimum price filter (>= 0) */
                    price_min?: number;
                    /** @description Maximum price filter (>= 0) */
                    price_max?: number;
                    /**
                     * @description Filter by schedule type:
                     *     - weekly: Recurring weekly schedules
                     *     - monthly: Recurring monthly schedules
                     *     - date_specific: One-time events
                     */
                    schedule_type?: "weekly" | "monthly" | "date_specific";
                    /**
                     * @description Filter by day of week (0-6):
                     *     0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday.
                     *     Cannot be used with day_of_month.
                     */
                    day_of_week_utc?: number;
                    /** @description Filter by day of month (1-31). Cannot be used with day_of_week_utc. */
                    day_of_month?: number;
                    /**
                     * @description Filter by start time (0-1439 minutes from midnight UTC).
                     *     Example: 600 = 10:00 AM UTC.
                     *     Must be less than end_minutes_utc when both provided.
                     */
                    start_minutes_utc?: number;
                    /**
                     * @description Filter by end time (0-1439 minutes from midnight UTC).
                     *     Example: 1080 = 6:00 PM UTC.
                     *     Must be greater than start_minutes_utc when both provided.
                     */
                    end_minutes_utc?: number;
                    /**
                     * @description Filter date-specific schedules starting at or after this time (ISO 8601).
                     *     Cannot be combined with day_of_week_utc or day_of_month.
                     */
                    start_at_utc?: string;
                    /**
                     * @description Filter date-specific schedules ending at or before this time (ISO 8601).
                     *     Cannot be combined with day_of_week_utc or day_of_month.
                     */
                    end_at_utc?: string;
                    /**
                     * @description Filter by language (ISO 639-1 codes). Multiple values allowed.
                     *     Supported: en, zh, ja, ko, fr, de, es, pt, it, ru, ar, hi, th, vi, id, ms, tl, nl, pl, tr, yue
                     */
                    language?: ("en" | "zh" | "ja" | "ko" | "fr" | "de" | "es" | "pt" | "it" | "ru" | "ar" | "hi" | "th" | "vi" | "id" | "ms" | "tl" | "nl" | "pl" | "tr" | "yue")[];
                    /** @description Maximum results per page (1-200, default 50) */
                    limit?: number;
                    /** @description Pagination cursor from previous response's next_cursor field */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivitySearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivitySearchResponse: {
            items: components["schemas"]["ActivitySearchResult"][];
            next_cursor?: string | null;
        };
        ActivitySearchResult: {
            activity: components["schemas"]["Activity"];
            organization: components["schemas"]["Organization"];
            location: components["schemas"]["Location"];
            pricing: components["schemas"]["Pricing"];
            schedule: components["schemas"]["Schedule"];
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            name_translations: components["schemas"]["TranslationMap"];
            description_translations: components["schemas"]["TranslationMap"];
            /** @description Cognito user sub of the organization manager */
            manager_id: string;
            media_urls: string[];
        };
        Location: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Geographic area UUID (leaf node)
             */
            area_id: string;
            address?: string | null;
            lat?: number | null;
            lng?: number | null;
        };
        Activity: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            name_translations: components["schemas"]["TranslationMap"];
            description_translations: components["schemas"]["TranslationMap"];
            age_min?: number | null;
            age_max?: number | null;
        };
        Pricing: {
            /** @enum {string} */
            pricing_type: "per_class" | "per_month" | "per_sessions";
            amount: number;
            currency: string;
            sessions_count?: number | null;
        };
        Schedule: {
            /** @enum {string} */
            schedule_type: "weekly" | "monthly" | "date_specific";
            day_of_week_utc?: number | null;
            day_of_month?: number | null;
            start_minutes_utc?: number | null;
            end_minutes_utc?: number | null;
            /** Format: date-time */
            start_at_utc?: string | null;
            /** Format: date-time */
            end_at_utc?: string | null;
            languages: string[];
        };
        /**
         * @description Language map for translated text. The server always includes English
         *     as "en" and may include additional languages like "zh" or "yue".
         */
        TranslationMap: {
            [key: string]: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
