# Checkov configuration for CDK infrastructure
# All checkov skips should be centralized in this file
# See: https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

# Framework configuration
framework:
  - cloudformation

# Soft fail - report issues without failing the build
soft-fail: true

# Skip checks - add justification for each skipped check
# Format:
#   skip-check:
#     - CKV_AWS_XXX:RESOURCE_ID  # Justification for skipping this check
#
# OrganizationImagesBucket skips:
# This S3 bucket is intentionally configured for public read access to serve
# organization images (logos, photos). The bucket uses BLOCK_ACLS to prevent
# ACL-based public access while allowing bucket policy based public read.
# This is a deliberate design choice for serving static assets.
# Future improvement: Consider using CloudFront with OAC for better security and caching.
#
# AdminWebLoggingBucket skips:
# This is a logging destination bucket that receives access logs from CloudFront
# and S3. Enabling access logging on a logging bucket would create an infinite
# loop of log entries. This is a standard AWS pattern.
skip-check:
  - CKV_AWS_54:AWS::S3::Bucket.OrganizationImagesBucket347D331B  # Public access intentional - serves organization images
  - CKV_AWS_55:AWS::S3::Bucket.OrganizationImagesBucket347D331B  # Public access intentional - serves organization images
  - CKV_AWS_56:AWS::S3::Bucket.OrganizationImagesBucket347D331B  # Public access intentional - serves organization images
  - CKV_AWS_18:AWS::S3::Bucket.AdminWebLoggingBucketF51DF562  # Logging bucket - enabling access logging would create infinite loop

# Compact output - reduce noise in CI logs
compact: true

# Download external modules/checks
download-external-modules: false
