# Checkov configuration for CDK infrastructure
# See: https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html
#
# IMPORTANT: Using skip-check to completely exclude checks from running.
# This prevents them from appearing in SARIF output (and thus GitHub Code Scanning).
# Inline metadata suppressions mark checks as "skipped" but still include them in SARIF.

# Framework configuration
framework:
  - cloudformation

# Soft fail - report issues without failing the build
soft-fail: true

# Compact output - reduce noise in CI logs
compact: true

# Download external modules/checks
download-external-modules: false

# Skip checks globally with justification
# These checks are skipped because they affect only CDK-internal resources
# or resources with intentional configurations that Checkov flags incorrectly.
#
# IMPORTANT: If you add new resources that should comply with these checks,
# you may need to remove the skip and use CDK metadata suppressions instead
# for the specific resources that need exceptions.
skip-check:
  # S3 bucket public access checks - ONLY affects OrganizationImagesBucket
  # This bucket intentionally allows public read access to serve organization
  # images (logos, photos). It uses BLOCK_ACLS to prevent ACL-based public
  # access while allowing bucket policy based public read.
  # Access is logged to OrganizationImagesLogBucket.
  # Future improvement: Consider using CloudFront with OAC.
  - CKV_AWS_54  # Block public policy
  - CKV_AWS_55  # Ignore public ACLs
  - CKV_AWS_56  # Restrict public buckets

  # S3 bucket access logging - ONLY affects logging buckets
  # AdminWebLoggingBucket and OrganizationImagesLogBucket are logging
  # destination buckets. Enabling access logging on them would create
  # an infinite loop. This is standard AWS practice.
  - CKV_AWS_18  # Access logging enabled

  # Lambda configuration checks - ONLY affects CDK-internal Lambda functions
  # LogRetention Lambda (manages CloudWatch log retention) and AwsCustomResource
  # Lambda (executes SDK calls for custom resources) are CDK-internal constructs.
  # They run only during deployments and don't need VPC, DLQ, or concurrency limits.
  - CKV_AWS_115  # Concurrent execution limit
  - CKV_AWS_116  # Dead Letter Queue
  - CKV_AWS_117  # VPC configuration

  # IAM policy constraint check - ONLY affects LogRetention Lambda
  # The LogRetention Lambda requires write access to CloudWatch Logs to manage
  # log group retention policies. This is a CDK-internal construct.
  - CKV_AWS_111  # Write access without constraints

  # RDS IAM authentication - ONLY affects Aurora cluster (not RDS Proxy)
  # IAM authentication is intentionally disabled on the Aurora cluster to allow
  # password-based connections for database migrations (Alembic). IAM auth is
  # enforced on the RDS Proxy for all Lambda application connections.
  # Architecture: Lambda -> RDS Proxy (IAM auth) -> Aurora Cluster (password auth)
  - CKV_AWS_162  # IAM authentication enabled
