# Checkov configuration for CDK infrastructure
# All checkov skips should be centralized in this file
# See: https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

# Framework configuration
framework:
  - cloudformation

# Soft fail - report issues without failing the build
soft-fail: true

# Skip checks - add justification for each skipped check
# Format:
#   skip-check:
#     - CKV_AWS_XXX:RESOURCE_ID  # Justification for skipping this check
#
# OrganizationImagesBucket skips:
# This S3 bucket is intentionally configured for public read access to serve
# organization images (logos, photos). The bucket uses BLOCK_ACLS to prevent
# ACL-based public access while allowing bucket policy based public read.
# This is a deliberate design choice for serving static assets.
# Future improvement: Consider using CloudFront with OAC for better security and caching.
#
# Logging bucket skips (AdminWebLoggingBucket, OrganizationImagesLogBucket):
# These are logging destination buckets that receive access logs from CloudFront
# and S3. Enabling access logging on a logging bucket would create an infinite
# loop of log entries. This is a standard AWS pattern.
#
# LogRetention Lambda skips:
# This is a CDK-internal Lambda function automatically created to manage
# CloudWatch log group retention policies. It's not user-managed code and
# runs infrequently (only during deployments), so concurrent execution
# limits are not necessary.
skip-check:
  - CKV_AWS_54:AWS::S3::Bucket.OrganizationImagesBucket347D331B  # Public access intentional - serves organization images
  - CKV_AWS_55:AWS::S3::Bucket.OrganizationImagesBucket347D331B  # Public access intentional - serves organization images
  - CKV_AWS_56:AWS::S3::Bucket.OrganizationImagesBucket347D331B  # Public access intentional - serves organization images
  - CKV_AWS_18:AWS::S3::Bucket.AdminWebLoggingBucketF51DF562  # Logging bucket - no self-logging to avoid infinite loop
  - CKV_AWS_18:AWS::S3::Bucket.OrganizationImagesLogBucket6FCE8FC4  # Logging bucket - no self-logging to avoid infinite loop
  - CKV_AWS_115:AWS::Lambda::Function.LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8aFD4BFC8A  # CDK internal - runs only during deployments
  - CKV_AWS_116:AWS::Lambda::Function.LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8aFD4BFC8A  # CDK internal - runs only during deployments

# Compact output - reduce noise in CI logs
compact: true

# Download external modules/checks
download-external-modules: false
