# Checkov configuration for CDK infrastructure
# See: https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html
#
# IMPORTANT: Checkov's skip-check option does NOT support resource-specific patterns.
# The format "CKV_ID:RESOURCE_ID" is NOT valid - only check IDs are supported.
# Resource-specific suppressions must be done via CloudFormation metadata in CDK code.
# See: lib/api-stack.ts and lib/admin-web-stack.ts for metadata-based suppressions.

# Framework configuration
framework:
  - cloudformation

# Soft fail - report issues without failing the build
soft-fail: true

# Compact output - reduce noise in CI logs
compact: true

# Download external modules/checks
download-external-modules: false

# NOTE: All resource-specific suppressions are now handled via CDK metadata:
#
# OrganizationImagesBucket (CKV_AWS_54, CKV_AWS_55, CKV_AWS_56):
#   - Public access is intentional - bucket serves organization images
#   - Suppressed in api-stack.ts via CfnBucket.addMetadata()
#
# AdminWebLoggingBucket, OrganizationImagesLogBucket (CKV_AWS_18):
#   - Logging buckets cannot have self-logging (infinite loop)
#   - Suppressed in admin-web-stack.ts and api-stack.ts via CfnBucket.addMetadata()
#
# LogRetention Lambda (CKV_AWS_115, CKV_AWS_116, CKV_AWS_117):
#   - CDK-internal Lambda for log retention management
#   - Runs only during deployments, no VPC/DLQ/concurrency needed
#   - Suppressed via CdkInternalLambdaCheckovSuppression Aspect in api-stack.ts
#
# LogRetention IAM Policy (CKV_AWS_111):
#   - CDK-internal policy for log retention management
#   - Requires write access to manage log groups
#   - Suppressed via CdkInternalLambdaCheckovSuppression Aspect in api-stack.ts
#
# AwsCustomResource Lambda (CKV_AWS_115, CKV_AWS_116, CKV_AWS_117):
#   - CDK-internal Lambda for custom resource SDK calls
#   - Runs only during deployments, no VPC/DLQ/concurrency needed
#   - Suppressed via CdkInternalLambdaCheckovSuppression Aspect in api-stack.ts
