export {
  createManagerActivity,
  createManagerLocation,
  createManagerPricing,
  createManagerSchedule,
  deleteManagerActivity,
  deleteManagerLocation,
  deleteManagerOrganization,
  deleteManagerPricing,
  deleteManagerSchedule,
  getManagerActivity,
  getManagerLocation,
  getManagerOrganization,
  getManagerPricing,
  getManagerSchedule,
  listManagerActivities,
  listManagerLocations,
  listManagerOrganizations,
  listManagerPricing,
  listManagerSchedules,
  updateManagerActivity,
  updateManagerLocation,
  updateManagerOrganization,
  updateManagerPricing,
  updateManagerSchedule,
} from './api-client';
