openapi: 3.0.3
info:
  title: Admin CRUD API
  version: 0.1.0
  description: CRUD endpoints for managing activities data.
paths:
  /admin/organizations:
    get:
      summary: List organizations
    post:
      summary: Create organization
  /admin/organizations/{id}:
    get:
      summary: Get organization
    put:
      summary: Update organization
    delete:
      summary: Delete organization
  /admin/locations:
    get:
      summary: List locations
    post:
      summary: Create location
  /admin/locations/{id}:
    get:
      summary: Get location
    put:
      summary: Update location
    delete:
      summary: Delete location
  /admin/activities:
    get:
      summary: List activities
    post:
      summary: Create activity
  /admin/activities/{id}:
    get:
      summary: Get activity
    put:
      summary: Update activity
    delete:
      summary: Delete activity
  /admin/pricing:
    get:
      summary: List pricing entries
    post:
      summary: Create pricing entry
  /admin/pricing/{id}:
    get:
      summary: Get pricing entry
    put:
      summary: Update pricing entry
    delete:
      summary: Delete pricing entry
  /admin/schedules:
    get:
      summary: List schedules
    post:
      summary: Create schedule
  /admin/schedules/{id}:
    get:
      summary: Get schedule
    put:
      summary: Update schedule
    delete:
      summary: Delete schedule
  /admin/users/{username}/groups:
    post:
      summary: Add user to group
    delete:
      summary: Remove user from group
