openapi: 3.0.3
info:
  title: Activities Search API
  version: 0.1.0
  description: |
    Search activities with filters for age, district, price, time, and language.

    ## Filter Validation Rules

    ### Numeric Ranges
    | Parameter | Range | Description |
    |-----------|-------|-------------|
    | age | >= 0 | Child's age to filter activities |
    | price_min | >= 0 | Minimum price filter |
    | price_max | >= 0 | Maximum price filter |
    | day_of_week_utc | 0-6 | Day of week (0=Sunday, 6=Saturday) |
    | start_minutes_utc | 0-1439 | Start time in minutes from midnight UTC |
    | end_minutes_utc | 0-1439 | End time in minutes from midnight UTC |
    | limit | 1-200 | Results per page (default 50) |

    ### Time Values
    Minutes are expressed as offset from midnight UTC:
    - 0 = 00:00 (midnight)
    - 60 = 01:00
    - 720 = 12:00 (noon)
    - 1439 = 23:59

    ### Filter Combinations
    - `start_minutes_utc` must be less than `end_minutes_utc` when both provided

paths:
  /v1/activities/search:
    get:
      summary: Search activities
      description: |
        Search for activities matching the specified filters.
        Results are paginated and ordered by schedule time.
      security:
        - ApiKeyAuth: []
          DeviceAttestation: []
      parameters:
        - name: age
          in: query
          required: false
          description: Filter activities suitable for this age (>= 0)
          schema:
            type: integer
            minimum: 0
        - name: area_id
          in: query
          required: false
          description: Filter by geographic area UUID
          schema:
            type: string
            format: uuid
        - name: pricing_type
          in: query
          required: false
          description: |
            Filter by pricing type:
            - per_class: Individual class pricing
            - per_sessions: Per term pricing
            - per_hour: Hourly pricing
            - per_day: Daily pricing
            - free: Free pricing
          schema:
            type: string
            enum: [per_class, per_sessions, per_hour, per_day, free]
        - name: price_min
          in: query
          required: false
          description: Minimum price filter (>= 0)
          schema:
            type: number
            format: decimal
            minimum: 0
        - name: price_max
          in: query
          required: false
          description: Maximum price filter (>= 0)
          schema:
            type: number
            format: decimal
            minimum: 0
        - name: schedule_type
          in: query
          required: false
          description: |
            Filter by schedule type:
            - weekly: Recurring weekly schedules
          schema:
            type: string
            enum: [weekly]
        - name: day_of_week_utc
          in: query
          required: false
          description: |
            Filter by day of week (0-6):
            0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday.
          schema:
            type: integer
            minimum: 0
            maximum: 6
        - name: start_minutes_utc
          in: query
          required: false
          description: |
            Filter by start time (0-1439 minutes from midnight UTC).
            Example: 600 = 10:00 AM UTC.
            Must be less than end_minutes_utc when both provided.
          schema:
            type: integer
            minimum: 0
            maximum: 1439
        - name: end_minutes_utc
          in: query
          required: false
          description: |
            Filter by end time (0-1439 minutes from midnight UTC).
            Example: 1080 = 6:00 PM UTC.
            Must be greater than start_minutes_utc when both provided.
          schema:
            type: integer
            minimum: 0
            maximum: 1439
        - name: language
          in: query
          required: false
          description: |
            Filter by language (ISO 639-1 codes plus yue (ISO 639-3)). Multiple values allowed.
            Supported: en, zh, ja, ko, fr, de, es, pt, it, ru, ar, hi, th, vi, id, ms, tl, nl, pl, tr, yue
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              enum: [en, zh, ja, ko, fr, de, es, pt, it, ru, ar, hi, th, vi, id, ms, tl, nl, pl, tr, yue]
        - name: limit
          in: query
          required: false
          description: Maximum results per page (1-200, default 50)
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 50
        - name: cursor
          in: query
          required: false
          description: Pagination cursor from previous response's next_cursor field
          schema:
            type: string
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivitySearchResponse"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    DeviceAttestation:
      type: apiKey
      in: header
      name: x-device-attestation
  schemas:
    ActivitySearchResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ActivitySearchResult"
        next_cursor:
          type: string
          nullable: true
    ActivitySearchResult:
      type: object
      required: [activity, organization, location, pricing, schedule]
      properties:
        activity:
          $ref: "#/components/schemas/Activity"
        organization:
          $ref: "#/components/schemas/Organization"
        location:
          $ref: "#/components/schemas/Location"
        pricing:
          $ref: "#/components/schemas/Pricing"
        schedule:
          $ref: "#/components/schemas/Schedule"
    Organization:
      type: object
      required:
        - id
        - name
        - name_translations
        - description_translations
        - manager_id
        - media_urls
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
          nullable: true
        name_translations:
          $ref: "#/components/schemas/TranslationMap"
        description_translations:
          $ref: "#/components/schemas/TranslationMap"
        manager_id:
          type: string
          description: Cognito user sub of the organization manager
        media_urls:
          type: array
          items:
            type: string
        logo_media_url:
          type: string
          format: uri
          nullable: true
          description: Optional logo media URL.
    Location:
      type: object
      required: [id, area_id]
      properties:
        id:
          type: string
          format: uuid
        area_id:
          type: string
          format: uuid
          description: Geographic area UUID (leaf node)
        address:
          type: string
          nullable: true
        lat:
          type: number
          nullable: true
        lng:
          type: number
          nullable: true
    Activity:
      type: object
      required: [id, name, name_translations, description_translations]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
          nullable: true
        name_translations:
          $ref: "#/components/schemas/TranslationMap"
        description_translations:
          $ref: "#/components/schemas/TranslationMap"
        age_min:
          type: integer
          nullable: true
        age_max:
          type: integer
          nullable: true
    Pricing:
      type: object
      required: [pricing_type, amount, currency, free_trial_class_offered]
      properties:
        pricing_type:
          type: string
          enum: [per_class, per_sessions, per_hour, per_day, free]
        amount:
          type: number
        currency:
          type: string
          description: ISO 4217 currency code (case-insensitive)
        sessions_count:
          type: integer
          nullable: true
        free_trial_class_offered:
          type: boolean
          description: Whether a free trial class is offered
    WeeklyScheduleEntry:
      type: object
      required: [day_of_week_utc, start_minutes_utc, end_minutes_utc]
      properties:
        day_of_week_utc:
          type: integer
          minimum: 0
          maximum: 6
        start_minutes_utc:
          type: integer
          minimum: 0
          maximum: 1439
        end_minutes_utc:
          type: integer
          minimum: 0
          maximum: 1439
    Schedule:
      type: object
      required: [schedule_type, weekly_entries, languages]
      properties:
        schedule_type:
          type: string
          enum: [weekly]
        weekly_entries:
          type: array
          items:
            $ref: "#/components/schemas/WeeklyScheduleEntry"
        languages:
          type: array
          items:
            type: string
    TranslationMap:
      type: object
      additionalProperties:
        type: string
      description: |
        Language map for translated text. The server always includes English as "en".
        Additional entries must use ISO 639-1 codes plus "yue" (Cantonese, ISO 639-3).
